spring.application.name=scms

#MySQL Database Conection
spring.datasource.url=jdbc:mysql://localhost:3306/scms_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate:auto  create /update tables
spring.jpa.hibernate.ddl-auto=update

#show sql quries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server port
server.port =8080